packages:
    - name: register
      environment: {
        BUDDAFEST_REGISTRATION_UI_URL:      ${BUDDAFEST_REGISTRATION_UI_URL},
        BUDDAFEST_REGISTRATION_S3_ENDPOINT: ${BUDDAFEST_REGISTRATION_S3_ENDPOINT},
        BUDDAFEST_REGISTRATION_S3_BUCKET:   ${BUDDAFEST_REGISTRATION_S3_BUCKET},
        BUDDAFEST_REGISTRATION_S3_ID:       ${BUDDAFEST_REGISTRATION_S3_ID},
        BUDDAFEST_REGISTRATION_S3_SECRET:   ${BUDDAFEST_REGISTRATION_S3_SECRET},
      }
      functions:
        - name: attendance
          runtime: go:default
